name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build docker image 
      run: docker build . --file Dockerfile --tag jdmunday/r_inla_sf_plus:$(date +%s)
    - name: Push docker image
      run: docker push jdmunday/r_inla_sf_plus:$(date +%s)
